set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

find_program(OPENDOOR_ARM64_C_COMPILER aarch64-linux-gnu-gcc REQUIRED)
set(CMAKE_C_COMPILER "${OPENDOOR_ARM64_C_COMPILER}")

set(OPENDOOR_ARM64_SYSROOT "$ENV{OPENDOOR_ARM64_SYSROOT}" CACHE PATH
    "Optional extracted ARM64 sysroot")
if(OPENDOOR_ARM64_SYSROOT)
  set(CMAKE_SYSROOT "${OPENDOOR_ARM64_SYSROOT}")
  set(CMAKE_FIND_ROOT_PATH
      "${OPENDOOR_ARM64_SYSROOT}"
      "${OPENDOOR_ARM64_SYSROOT}/usr/aarch64-linux-gnu"
      "${OPENDOOR_ARM64_SYSROOT}/usr/lib/aarch64-linux-gnu")
else()
  set(CMAKE_FIND_ROOT_PATH
      /usr/aarch64-linux-gnu
      /usr/lib/aarch64-linux-gnu)
endif()
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
